### ISSUE TITLE
type 'Null' is not a subtype of type 'Widget' in type cast, List<Widget> rendering  problem

### ISSUE THREAD

**Issue by OpencvLZG** [gskinner/flutter_animate#91]
`for (int i = 0; i < viewList.length; i++) {
          widgets.add(BuildListItem(i));
        }
        _isLoadding = false;
        _fectching = false;

        widgets = widgets
            .animate(
              interval: 300.ms,
            )
            .fadeIn(
              duration: 900.ms,
            )
            .move(begin: const Offset(-16, 0), curve: Curves.easeOutQuad);`
I want rendering dynamic List<Widget>, if rendering  twice will happen type 'Null' is not a subtype of type 'Widget' in type cast,only rendering  once will not throw, but when i add again element, and widgets = widgets.animate(),it will throw expection

**Comment by gskinner** [comment]
Apologies, I'm not totally following. It sounds like you might have null entries in your `widgets` list. I'm fairly certain there's no way for AnimateList to return a null widget. Perhaps if you provide a stack trace that would help?

**Comment by OpencvLZG** [comment]
`[Padding(padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)), Padding(padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)), Padding(padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)), Padding(padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)), Padding(padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)), Padding(padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)), Padding(padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)), Padding(padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)), Padding(padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)), Padding(padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)), Padding(padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)), Padding(padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)), Padding(padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)), Padding(padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)), Padding(padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)), Padding(padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)), Padding(padding: EdgeInsets(0.0, 8.0, 0.0, 0.0))]`

this is the widgets,and expection

`The following _CastError was thrown while dispatching notifications for ScrollController:
type 'Null' is not a subtype of type 'Widget' in type cast

When the exception was thrown, this was the stack
#0      List.length= (dart:core-patch/growable_array.dart:229:12)
#1      AnimateList.length=
#2      ListMixin.add (dart:collection/list.dart:279:15)
#3      _ViewListState._fetchData.<anonymous closure>
#4      State.setState
#5      _ViewListState._fetchData
#6      _ViewListState._scrollListener
#7      ChangeNotifier.notifyListeners
#8      ChangeNotifier.notifyListeners
#9      ScrollPosition.notifyListeners
#10     ScrollPosition.setPixels
#11     ScrollPositionWithSingleContext.setPixels
#12     BallisticScrollActivity.applyMoveTo
#13     BallisticScrollActivity._tick
#14     AnimationLocalListenersMixin.notifyListeners
#15     AnimationController._tick
#16     Ticker._tick
#17     SchedulerBinding._invokeFrameCallback
#18     SchedulerBinding.handleBeginFrame.<anonymous closure>
#19     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#20     SchedulerBinding.handleBeginFrame
#21     SchedulerBinding._handleBeginFrame
#22     _invoke1 (dart:ui/hooks.dart:164:13)
#23     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:316:5)
#24     _beginFrame (dart:ui/hooks.dart:101:31)
The ScrollController sending notification was: ScrollController#81d43(one client, offset 925.0)`
I give up use Grammatical sugar,now that i use this way, and it can working
`AnimateList(
      interval: 400.ms,
      effects: [
        FadeEffect(duration: 300.ms),
        MoveEffect(
            duration: 500.ms,
            begin: const Offset(-16, 0),
            curve: Curves.easeOutQuad),
        ShimmerEffect(delay: 300.ms, color: Colors.white70)
      ],
      children: widgets,
    );`

complete code here, sry that it may be like clutter

`import 'package:cil_vpn/models/constants.dart';
import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'dart:async';
import '../../../../../models/viewList.dart';

class ViewList extends StatefulWidget {
  const ViewList({super.key});

  @override
  State<ViewList> createState() => _ViewListState();
}

class _ViewListState extends State<ViewList> {
  bool _isLoadding = true;
  bool _fectching = true;

  List<Widget> widgets = [];

  final scrollController = ScrollController();

  @override
  Widget build(BuildContext context) {
    return Animate(
      child: Container(
          margin: EdgeInsets.all(kDefaultPadding),
          height: 500,
          child: ListView(
            controller: scrollController,
            children: _isLoadding ? BuildShimmerListItem() : widgets,
          )),
    ).fadeIn();
  }

  void _scrollListener() {
    if (scrollController.position.pixels ==
        scrollController.position.maxScrollExtent) {
      print("call");
      _fetchData();
    } else {}
  }

  void _fetchData() {
    Timer(Duration(seconds: 3), () {
      setState(() {
        _fectching = true;
      });
    });
    setState(() {
      // widgets.clear();
      if (_fectching) {
        for (int i = 0; i < viewList.length; i++) {
          widgets.add(BuildListItem(i));
        }
        _isLoadding = false;
        _fectching = false;
        print(widgets);
        widgets = widgets
            .animate(
              interval: 300.ms,
            )
            .fadeIn(
              duration: 900.ms,
            )
            .move(begin: const Offset(-16, 0), curve: Curves.easeOutQuad);
        widgets = widgets
            .animate(
              interval: 300.ms,
            )
            .fadeIn(
              duration: 900.ms,
            )
            .move(begin: const Offset(-16, 0), curve: Curves.easeOutQuad);
        print(widgets);
      }
    });
  }

  @override
  void initState() {
    scrollController.addListener(_scrollListener);
  }

  List<Widget> BuildShimmerListItem() {
    Widget widgetItem = Padding(
      padding: const EdgeInsets.only(top: 10),
      child: GestureDetector(
        onTap: () {},
        child: Container(
          // height: 75,
          decoration: BoxDecoration(
            border: Border(
                bottom: BorderSide(
                    color: Colors.black, width: 1, style: BorderStyle.solid)),
          ),
          child: Row(
            children: [
              Column(
                mainAxisAlignment: MainAxisAlignment.start,
                children: [
                  Container(
                    width: 50,
                    height: 50,
                    decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(300),
                        color: kShadowShimmerColor),
                  ),
                  Container(
                    margin: EdgeInsets.all(10),
                    width: 50,
                    height: 15,
                    decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(300),
                        color: kShadowShimmerColor),
                  )
                ],
              ),
              Container(
                padding: EdgeInsets.only(left: 8),
                width: MediaQuery.of(context).size.width * 0.7,
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.spaceAround,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Container(
                      margin: EdgeInsets.only(bottom: 7),
                      width: 100,
                      height: 15,
                      decoration: BoxDecoration(
                          color: kShadowShimmerColor,
                          borderRadius: BorderRadius.circular(300)),
                    ),
                    Container(
                      margin: EdgeInsets.only(bottom: 4),
                      height: 10,
                      decoration: BoxDecoration(
                          color: kShadowShimmerColor,
                          borderRadius: BorderRadius.circular(300)),
                    ),
                    Container(
                      margin: EdgeInsets.only(bottom: 4),
                      height: 10,
                      decoration: BoxDecoration(
                          color: kShadowShimmerColor,
                          borderRadius: BorderRadius.circular(300)),
                    ),
                    Container(
                      margin: EdgeInsets.only(top: 8),
                      width: 100,
                      height: 8,
                      decoration: BoxDecoration(
                          color: kShadowShimmerColor,
                          borderRadius: BorderRadius.circular(300)),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
    List<Widget> shimmerList = [];
    for (int i = 0; i < 10; i++) {
      shimmerList.add(Animate(
        child: widgetItem,
        onPlay: (controller) => controller.repeat(),
      ).shimmer(duration: 800.ms, color: Colors.blue));
    }
    shimmerList = shimmerList
        .animate(
          interval: 300.ms,
        )
        .fadeIn(
          duration: 900.ms,
        )
        .move(begin: const Offset(-16, 0), curve: Curves.easeOutQuad);
    return shimmerList;
  }

  Widget BuildListItem(int index) {
    Widget widget = Padding(
      padding: const EdgeInsets.only(top: 8.0),
      child: GestureDetector(
        onTap: () {},
        child: Container(
          // height: 75,
          decoration: BoxDecoration(
            border: Border(
                bottom: BorderSide(
                    color: Colors.black, width: 1, style: BorderStyle.solid)),
          ),
          child: Row(
            children: [
              Column(
                mainAxisAlignment: MainAxisAlignment.start,
                children: [
                  Container(
                    width: 50,
                    height: 50,
                    decoration: BoxDecoration(
                        boxShadow: [kDefaultShadow],
                        borderRadius: BorderRadius.circular(300),
                        image: DecorationImage(
                            image: NetworkImage(viewList[index][2]),
                            fit: BoxFit.cover)),
                  ),
                  Text(
                    viewList[index][1],
                    style: kDefaultTextStyle,
                  ),
                ],
              ),
              Container(
                padding: EdgeInsets.only(left: 8),
                width: MediaQuery.of(context).size.width * 0.7,
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      viewList[index][0],
                      style: kDefaultTextStyle,
                    ),
                    Text(
                      "\t  ${viewList[index][3]}",
                      textAlign: TextAlign.left,
                      style: kDefaultArticleStyle,
                      maxLines: 2,
                      overflow: TextOverflow.visible,
                    ),
                    Text(
                      viewList[index][4],
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );

    return Animate(
      child: widget,
    ).fade().move(begin: const Offset(-16, 0), curve: Curves.easeOutQuad);
  }
}
`

**Comment by gskinner** [comment]
Hmm. I can't think of any way that switching from the `.animate()` extension to using the `AnimateList` constructor could have fixed anything. The extension doesn't do anything but call the constructor with the same arguments. Are you sure you didn't change anything else?

**Comment by OpencvLZG** [comment]
Sry that Something happened that caused me not to recover you in time
I write a new test, when bugTrigger is true, it will make a err
when use AnimateList,the err will not made
```
import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Widget> widgets = [];
  bool bugTrigger = true;
  void _addList() {
    setState(() {
      for (var i = 0; i < 10; i++) {
        widgets.add(Container(
          child: Text("Hi"),
        ));
      }
      if (bugTrigger) {
        widgets = widgets.animate(interval: 200.ms);
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          children: bugTrigger ? widgets : AnimateList(children: widgets),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _addList,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by gskinner** [comment]
You probably shouldn't be constructing widgets outside your build stack.
